pipeline {
    agent any

    stages {

        stage('Repository Check') {
            steps {
                echo 'GitHub connected successfully'
            }
        }

        stage('Show Project Files') {
            steps {
                bat 'dir'
            }
        }

        stage('Pipeline Test') {
            steps {
                echo 'CI/CD Pipeline is working'
            }
        }
    }
}