pipeline {
agent any

```
tools {
    nodejs 'NodeJS'
}

environment {
    SONAR_TOKEN = credentials('sonar-token')
}

stages {

    stage('Checkout Code') {
        steps {
            git branch: 'main',
            url: 'https://github.com/ramyamahendra332-sudo/EcommerceApp1.git'
        }
    }

    stage('Install Dependencies') {
        steps {
            bat 'npm install'
        }
    }

    stage('Build Application') {
        steps {
            bat 'npm run build'
        }
    }

    stage('SonarQube Analysis') {
        steps {
            withSonarQubeEnv('SonarQube') {
                bat '''
                sonar-scanner ^
                -Dsonar.projectKey=EcommerceApp1 ^
                -Dsonar.sources=src ^
                -Dsonar.login=%SONAR_TOKEN%
                '''
            }
        }
    }

    stage('Deploy to Tomcat') {
        steps {
            bat '''
            rmdir /s /q "C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps\\ROOT"
            xcopy build "C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps\\ROOT\\" /E /I /Y
            '''
        }
    }
}

post {
    success {
        echo 'Build Successful'
        echo 'Application Deployed to Tomcat'
    }

    failure {
        echo 'Build Failed'
    }
}
```

}
