name: SonarCloud Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # IMPORTANT STEP (THIS FIXES YOUR ERROR)
      - name: Build Maven project
        run: mvn clean compile package

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=EcommerceApp1
            -Dsonar.organization=ramyamahendra332-sudo
            -Dsonar.java.binaries=target/classes
